
name: Ansible Django Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.10.7 requests
    - name: set ansible config secrets
      env:        
        SSH_KEY: ${{ secrets.DJANGO_SSH_KEY }}
      run: |
        echo "$SSH_KEY" > ./id_django
        chmod 600 ./id_django
    - name: debug print ssh key
      run: cat ./id_django
    - name: run deployment playbook
      run: |
        ansible-playbook -i inventory deployproject.yml
